# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 20:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True)),
                ('type', models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video'), ('Text', 'Text')], max_length=16)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('youtube_url', models.URLField(blank=True)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
