# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('photo', 'Foto'), ('video', 'Video'), ('text', 'Tekst'), ('header', 'Header'), ('tickets', 'Tickets')], help_text='Kies hier het type element. Een foto-element lat een foto zien, een video element een video, etc.', max_length=16),
        ),
    ]
